#!/bin/sh

export PATH=/sbin:/bin:/usr/sbin:/usr/bin

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts /run /tmp
mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /run
mount -t tmpfs tmpfs /tmp

if [ -w /proc/sys/kernel/hotplug ]; then
  echo /sbin/mdev > /proc/sys/kernel/hotplug
fi
mdev -s

echo "Nyabula AMP compute domain ready"
exec /sbin/init
