#!/usr/bin/env python3

"""Generate the fixed-size LVGL font subsets used by the eye scenes."""

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path


FONT_MATRIX = {
    "title": ("AlimamaShuHeiTi.ttf", (20, 28, 42)),
    "body": ("MiSans-Semibold.ttf", (14, 18)),
    "english": ("Tinos-Bold.ttf", (18, 42, 72, 96, 119)),
}


def collect_symbols(paths):
    content = "".join(
        path.read_text(encoding="utf-8")
        for path in paths
    )
    return "".join(sorted({
        char for char in content
        if "\u3400" <= char <= "\u9fff" or char in "，。！？·℃°"
    }))


def sanitize_metadata(output):
    lines = output.read_text(encoding="utf-8").splitlines()
    while lines and not lines[-1]:
        lines.pop()
    lines = [
        " * Generated by app/nyabula/tools/generate_fonts.py."
        if line.startswith(" * Opts:") else line
        for line in lines
    ]
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def generate(html, font_dir, output_dir):
    app_dir = Path(__file__).resolve().parents[1]
    sources = [html]
    sources.extend(sorted((app_dir / "src").rglob("*.c")))
    sources.extend(sorted((app_dir / "include").rglob("*.h")))
    symbols = collect_symbols(sources)
    converter = shutil.which("npx.cmd") or shutil.which("npx")
    if converter is None:
        raise FileNotFoundError("npx")
    output_dir.mkdir(parents=True, exist_ok=True)
    for family, (filename, sizes) in FONT_MATRIX.items():
        font = font_dir / filename
        if not font.is_file():
            raise FileNotFoundError(font)
        for size in sizes:
            name = f"nyabula_font_{family}_{size}"
            output = output_dir / f"{name}.c"
            command = [
                converter, "--yes", "lv_font_conv",
                "--font", str(font),
                "-r", "0x20-0x7e",
            ]
            if family != "english":
                command.extend(["--symbols", symbols])
            else:
                command.extend(["--symbols", "°"])
            command.extend([
                "--size", str(size),
                "--bpp", "4",
                "--no-compress",
                "--format", "lvgl",
                "--lv-include", "lvgl/lvgl.h",
                "--lv-font-name", name,
                "-o", str(output),
            ])
            subprocess.run(command, check=True)
            sanitize_metadata(output)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("html", type=Path)
    parser.add_argument("font_dir", type=Path)
    parser.add_argument("output_dir", type=Path)
    args = parser.parse_args()
    generate(args.html, args.font_dir, args.output_dir)


if __name__ == "__main__":
    main()
