/****************************************************************************
 * chips/rk3576/rk3576_vop.c
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/****************************************************************************
 * RK3576 Video Output Processor (VOP) framebuffer driver.
 *
 * Implements the NuttX generic framebuffer framework (struct fb_vtable_s)
 * on top of the RK3576 VOP (TRM Part 2, Chapter 11 "VOP_LITE").
 *
 * Minimal scope: a single CLUSTER0_WIN0 RGB888 layer scanned out through
 * one video port (POSTx) to one physical output interface.  No MMU, no
 * ESMART, no compression, no alpha blending, no vsync interrupt.
 *
 * The framebuffer is allocated from the RK3576 DMA heap
 * (rk3576_dma_alloc): the WIN0 YRGB_MST register is a 32-bit physical
 * address (MMU bypass), so the buffer must be physically contiguous and
 * below 4GB.
 *
 * The VOP is shared by multiple output interfaces.  Routing is expressed
 * as an (iface, port) pair; each RK3576_VOP_IFACE_* id maps to a
 * SYS_CTRL_*_INFACE_CTRL register offset in g_rk3576_vop_iface_regs, and
 * the same field layout (port_sel/out_en) is applied uniformly.
 ****************************************************************************/

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>

#include <assert.h>
#include <debug.h>
#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include <syslog.h>

#include <nuttx/arch.h>
#include <nuttx/clk/clk.h>
#include <nuttx/compiler.h>
#include <nuttx/kmalloc.h>
#include <nuttx/mutex.h>
#include <nuttx/video/fb.h>

#include "arm64_arch.h"
#include "hardware/rk3576_cru.h"
#include "hardware/rk3576_memorymap.h"
#include "hardware/rk3576_vop.h"
#include "rk3576_addrenv.h"
#include "rk3576_dma_alloc.h"
#include "rk3576_vop.h"

#ifdef CONFIG_RK3576_VOP

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* VOP bus clocks (registered by rk3576_clk_register_vop()). */

#define RK3576_VOP_ACLK_NAME "aclk_vop"
#define RK3576_VOP_HCLK_NAME "hclk_vop"
#define RK3576_VOP_PCLK_NAME "pclk_vop_root"

/* VOP core resets (active-low, hiword-mask write scheme).
 * SOFTRST_CON61: aresetn_vop[9], hresetn_vop[8], presetn_vop_biu[7],
 *                hresetn_vop_biu[6], aresetn_vop_biu[4].
 */

#define RK3576_VOP_RST_CON         61
#define RK3576_VOP_RST_DRESETN_VP0 (1 << 13)
#define RK3576_VOP_RST_ARESETN_VOP (1 << 9)
#define RK3576_VOP_RST_HRESETN_VOP (1 << 8)
#define RK3576_VOP_RST_PRESETN_BIU (1 << 7)
#define RK3576_VOP_RST_HRESETN_BIU (1 << 6)
#define RK3576_VOP_RST_ARESETN_BIU (1 << 4)
#define RK3576_VOP_RST_MAIN_MASK                             \
  (RK3576_VOP_RST_DRESETN_VP0 | RK3576_VOP_RST_ARESETN_VOP | \
   RK3576_VOP_RST_HRESETN_VOP | RK3576_VOP_RST_PRESETN_BIU | \
   RK3576_VOP_RST_HRESETN_BIU | RK3576_VOP_RST_ARESETN_BIU)

/* Hiword-mask write: bits [31:16] are the write-enable mask. */

#define RK3576_VOP_HWM(bits) ((bits) << 16)

/* PMU power-domain control (PMU base + PWR_GATE_CON0).  The ESMART layer
 * lives in its own power domain (PD_VOP_ESMART) inside the VOP; its AXI
 * clock (aclk_esmart0..3) is generated by the VOP-internal ESMART_PD_CRU
 * once the domain is powered.  There is no standalone aclk_esmart gate in
 * the CRU -- the whole esmart clock tree hangs off aclk_vop (already
 * enabled below), so the missing piece is the power-domain + frame reset.
 *
 * PMU_PWR_GATE_CON0 (0x27360000 + 0x20200):
 *   bit 12  pd_vop_esmart_dwn_ena  ('0' = keep PD_VOP_ESMART powered)
 *   bit 11  pd_vop_dwn_ena         ('0' = keep PD_VOP powered)
 *
 * Writes use the hiword-mask scheme: bits [31:16] mask which low bits are
 * written.  Clearing a *_dwn_ena bit (mask=1, data=0) keeps the domain up.
 */

#define RK3576_VOP_PMU_PWR_GATE_CON0_OFF  0x20200
#define RK3576_VOP_PD_VOP_ESMART_DWN_ENA   (1 << 12)
#define RK3576_VOP_PD_VOP_DWN_ENA          (1 << 11)

/* Memory-repair initial reset (BISR initrst).  These bits gate the PD-level
 * reset (aresetn_pd in the VOP cluster/esmart block diagrams, Fig 11-14/15):
 *   PMU_BISR_INITRST_SFTCON0 = 0x27360000 + 0x20540
 *     bit 13  pd_vop_cluster_initrst_sftena  (1 = Normal, release reset)
 *     bit 12  pd_vop_esmart_initrst_sftena   (1 = Normal, release reset)
 *     bit 11  pd_vop_initrst_sftena          (1 = Normal, release reset)
 * Reset value 0 => held in RESET; the driver MUST set these to 1, otherwise
 * the ESMART/POST layer clocks (aclk_esmart0..3, derived from aclk_vop by
 * ESMART_PD_CRU) never come up and every ESMART register reads back 0.
 */

#define RK3576_VOP_PMU_BISR_INITRST_SFTCON0_OFF 0x20540
#define RK3576_VOP_PD_VOP_CLUSTER_INITRST (1 << 13)
#define RK3576_VOP_PD_VOP_ESMART_INITRST  (1 << 12)
#define RK3576_VOP_PD_VOP_INITRST         (1 << 11)
#define RK3576_VOP_INITRST_RELEASE_MASK                     \
  (RK3576_VOP_PD_VOP_CLUSTER_INITRST |                      \
   RK3576_VOP_PD_VOP_ESMART_INITRST | RK3576_VOP_PD_VOP_INITRST)

/****************************************************************************
 * Private Types
 ****************************************************************************/

/* Framebuffer driver instance.  The vtable is the first member so the
 * fb framework's struct fb_vtable_s * can be cast back via container_of.
 */

struct rk3576_vop_s
{
  struct fb_vtable_s vtable;    /* Must be first */
  uintptr_t base;               /* VOP base (0x27D00000) */
  struct clk_s *aclk;           /* aclk_vop */
  struct clk_s *hclk;           /* hclk_vop */
  struct clk_s *dclk;           /* dclk_vpN (pixel clock) */
  struct rk3576_vop_config cfg; /* Routing/geometry configuration */
  void *fbmem;                  /* Framebuffer (DMA heap) */
  size_t fblen;                 /* Framebuffer length in bytes */
  uint32_t stride;              /* Line stride in bytes */
};

/****************************************************************************
 * Private Data
 ****************************************************************************/

/* Map logical interface id -> SYS_CTRL_*_INFACE_CTRL register offset.
 * Indexed by enum rk3576_vop_iface_e.
 */

static const uint32_t g_rk3576_vop_iface_regs[RK3576_VOP_IFACE_MAX] = {
  RK3576_VOP_MIPI0_INFACE_CTRL, /* RK3576_VOP_IFACE_MIPI_DSI */
  RK3576_VOP_HDMI0_INFACE_CTRL, /* RK3576_VOP_IFACE_HDMI */
  RK3576_VOP_EDP0_INFACE_CTRL,  /* RK3576_VOP_IFACE_EDP */
  RK3576_VOP_DP0_INFACE_CTRL,   /* RK3576_VOP_IFACE_DP */
  RK3576_VOP_RGB_INFACE_CTRL,   /* RK3576_VOP_IFACE_RGB */
};

/* Pixel clock name per video port (registered by rk3576_clk_register_vop). */

static const char *g_rk3576_vop_dclk_names[3] = {
  "dclk_vp0", /* RK3576_VOP_PORT0 */
  "dclk_vp1", /* RK3576_VOP_PORT1 */
  "dclk_vp2", /* RK3576_VOP_PORT2 */
};

/****************************************************************************
 * Private Function Prototypes
 ****************************************************************************/

static int rk3576_vop_getvideoinfo(FAR struct fb_vtable_s *vtable,
                                   FAR struct fb_videoinfo_s *vinfo);
static int rk3576_vop_getplaneinfo(FAR struct fb_vtable_s *vtable, int planeno,
                                   FAR struct fb_planeinfo_s *pinfo);
static int rk3576_vop_open(FAR struct fb_vtable_s *vtable);
static int rk3576_vop_close(FAR struct fb_vtable_s *vtable);
static int rk3576_vop_setpower(FAR struct fb_vtable_s *vtable, int power);

/****************************************************************************
 * Private Data
 ****************************************************************************/

/* Framebuffer vtable (only the callbacks exercised by the fb framework's
 * char driver are wired here; advanced features are intentionally left
 * NULL so the framework reports -ENOTTY where appropriate).
 */

static const struct fb_vtable_s g_rk3576_vop_vtable = {
  .getvideoinfo = rk3576_vop_getvideoinfo,
  .getplaneinfo = rk3576_vop_getplaneinfo,
  .open = rk3576_vop_open,
  .close = rk3576_vop_close,
  .setpower = rk3576_vop_setpower,
};

/****************************************************************************
 * Private Functions
 ****************************************************************************/

/****************************************************************************
 * Name: rk3576_vop_getreg / putreg / modifyreg
 *
 * Description:
 *   Register accessors.  The "reg" parameter is an *absolute* address,
 *   already composed from the VOP base plus one of the RK3576_VOP_*()
 *   address macros (which receive priv->base as their base argument).
 *   Callers pass e.g. RK3576_VOP_POST(priv->base, port) + POST_*_OFFSET,
 *   so these helpers must NOT add priv->base again (that would duplicate
 *   the base into the address).
 ****************************************************************************/

static uint32_t rk3576_vop_getreg(struct rk3576_vop_s *priv,
                                  unsigned int reg)
{
  return getreg32(reg);
}

static void rk3576_vop_putreg(struct rk3576_vop_s *priv, unsigned int reg,
                              uint32_t value)
{
  putreg32(value, reg);
}

static void rk3576_vop_modifyreg(struct rk3576_vop_s *priv,
                                 unsigned int reg, uint32_t clrbits,
                                 uint32_t setbits)
{
  uint32_t regval = rk3576_vop_getreg(priv, reg);

  regval &= ~clrbits;
  regval |= setbits;
  rk3576_vop_putreg(priv, reg, regval);
}

/****************************************************************************
 * Name: rk3576_vop_getvideoinfo
 ****************************************************************************/

static int rk3576_vop_getvideoinfo(FAR struct fb_vtable_s *vtable,
                                   FAR struct fb_videoinfo_s *vinfo)
{
  FAR struct rk3576_vop_s *priv = (FAR struct rk3576_vop_s *)vtable;

  DEBUGASSERT(vtable != NULL);
  DEBUGASSERT(vinfo != NULL);

  vinfo->fmt = FB_FMT_RGB24;
  vinfo->xres = priv->cfg.xres;
  vinfo->yres = priv->cfg.yres;
  vinfo->nplanes = 1;

  return OK;
}

/****************************************************************************
 * Name: rk3576_vop_getplaneinfo
 ****************************************************************************/

static int rk3576_vop_getplaneinfo(FAR struct fb_vtable_s *vtable, int planeno,
                                   FAR struct fb_planeinfo_s *pinfo)
{
  FAR struct rk3576_vop_s *priv = (FAR struct rk3576_vop_s *)vtable;

  DEBUGASSERT(vtable != NULL);
  DEBUGASSERT(pinfo != NULL);

  if (planeno != 0)
    {
      return -EINVAL;
    }

  pinfo->fbmem = priv->fbmem;
  pinfo->fblen = priv->fblen;
  pinfo->stride = priv->stride;
  pinfo->display = priv->cfg.display;
  pinfo->bpp = 24;
  pinfo->xres_virtual = priv->cfg.xres;
  pinfo->yres_virtual = priv->cfg.yres;
  pinfo->xoffset = 0;
  pinfo->yoffset = 0;

  return OK;
}

/****************************************************************************
 * Name: rk3576_vop_open / close
 ****************************************************************************/

static int rk3576_vop_open(FAR struct fb_vtable_s *vtable) { return OK; }

static int rk3576_vop_close(FAR struct fb_vtable_s *vtable) { return OK; }

/****************************************************************************
 * Name: rk3576_vop_setpower
 ****************************************************************************/

static int rk3576_vop_setpower(FAR struct fb_vtable_s *vtable, int power)
{
  FAR struct rk3576_vop_s *priv = (FAR struct rk3576_vop_s *)vtable;
  uint32_t post_base = RK3576_VOP_POST(priv->base, priv->cfg.port);

  DEBUGASSERT(vtable != NULL);

  /* power == 0 -> black display (dsp_black_en); power != 0 -> normal. */

  if (power == 0)
    {
      rk3576_vop_modifyreg(priv, post_base + RK3576_VOP_POST_DSP_CTRL, 0,
                           RK3576_VOP_POST_BLACK_EN);
    }
  else
    {
      rk3576_vop_modifyreg(priv, post_base + RK3576_VOP_POST_DSP_CTRL,
                           RK3576_VOP_POST_BLACK_EN, 0);
    }

  return OK;
}

/****************************************************************************
 * Name: rk3576_vop_configure_timing
 *
 * Description:
 *   Program the POSTx timing registers (HTOTAL/HACT/VTOTAL/VACT) from the
 *   configuration's porch/sync values.  Layout follows the Rockchip
 *   convention where each *_TOTAL_*_END register packs {total[28:16],
 *   sync_end[12:0]} and each *_ACT_ST_END packs {start[28:16], end[12:0]}.
 ****************************************************************************/

static void rk3576_vop_configure_timing(FAR struct rk3576_vop_s *priv)
{
  uint32_t post_base = RK3576_VOP_POST(priv->base, priv->cfg.port);
  uint16_t xres = priv->cfg.xres;
  uint16_t yres = priv->cfg.yres;

  uint16_t htotal = xres + priv->cfg.hsync_len + priv->cfg.hfront_porch +
                    priv->cfg.hback_porch;
  uint16_t vtotal = yres + priv->cfg.vsync_len + priv->cfg.vfront_porch +
                    priv->cfg.vback_porch;

  uint16_t hs_end = priv->cfg.hsync_len - 1;
  uint16_t hact_st = priv->cfg.hsync_len + priv->cfg.hback_porch;
  uint16_t hact_end = hact_st + xres - 1;

  uint16_t vs_end = priv->cfg.vsync_len - 1;
  uint16_t vact_st = priv->cfg.vsync_len + priv->cfg.vback_porch;
  uint16_t vact_end = vact_st + yres - 1;

  /* HTOTAL_HS_END: {total[28:16], hs_end[12:0]} */

  rk3576_vop_putreg(priv, post_base + RK3576_VOP_POST_DSP_HTOTAL_HS_END,
                    ((uint32_t)(htotal - 1) << 16) | (hs_end & 0x1fff));

  /* HACT_ST_END: {start[28:16], end[12:0]} */

  rk3576_vop_putreg(priv, post_base + RK3576_VOP_POST_DSP_HACT_ST_END,
                    ((uint32_t)hact_st << 16) | (hact_end & 0x1fff));

  /* VTOTAL_VS_END: {total[28:16], vs_end[12:0]} */

  rk3576_vop_putreg(priv, post_base + RK3576_VOP_POST_DSP_VTOTAL_VS_END,
                    ((uint32_t)(vtotal - 1) << 16) | (vs_end & 0x1fff));

  /* VACT_ST_END: {start[28:16], end[12:0]} */

  rk3576_vop_putreg(priv, post_base + RK3576_VOP_POST_DSP_VACT_ST_END,
                    ((uint32_t)vact_st << 16) | (vact_end & 0x1fff));
}

/****************************************************************************
 * Name: rk3576_vop_configure_layer
 *
 * Description:
 *   Configure a single ESMART REGION0 to scan out an RGB888 framebuffer,
 *   route it into the selected video port's OVERLAY layer0, and fire the
 *   register-configure-done pulse so all mirror registers take effect at
 *   the start of the next frame.
 *
 *   The ESMART layer (not CLUSTER) is used because it is the plain
 *   uncompressed raster window -- the natural fit for a regular RGB
 *   framebuffer (no FBCD compression state machine to bring up).
 ****************************************************************************/

static void rk3576_vop_configure_layer(FAR struct rk3576_vop_s *priv)
{
  uint32_t esmart_base = RK3576_VOP_ESMART(priv->base, 0);
  uint32_t ovl_base = RK3576_VOP_OVERLAY_PORT(priv->base, priv->cfg.port);
  uint16_t xres = priv->cfg.xres;
  uint16_t yres = priv->cfg.yres;
  uint32_t vir_stride; /* stride in words (4 bytes) */
  uint32_t ctrl;

  /* AXI control: MMU bypass (REGION0_YRGB_MST is a physical address) and
   * let the hardware auto-optimise DMA bursts that cross a 4k boundary.
   *
   * CRITICAL: also bound the AXI outstanding transactions.  At reset the
   * ESMART AXI outstanding_en=0, which means *unlimited* bursts -- once the
   * scan-out DMA starts reading the framebuffer it floods the AXI/NoC and
   * starves the CPU's DDR traffic, hanging the SoC right after nsh starts.
   * outstanding_en=1 + num=4 keeps the bursts bounded.
   */

  rk3576_vop_putreg(priv, esmart_base + RK3576_VOP_ESMART_AXI_CTRL_IMD,
                    RK3576_VOP_ESMART_AXI_DMA_4K_ADDR_OPT |
                        RK3576_VOP_ESMART_AXI_MMU_BYPASS |
                        RK3576_VOP_ESMART_AXI_OUTSTANDING_EN |
                        RK3576_VOP_ESMART_AXI_OUTSTANDING(4));

  /* REGION0 disabled first, RGB888 format. */

  rk3576_vop_putreg(priv, esmart_base + RK3576_VOP_ESMART_REGION0_CTRL,
                    RK3576_VOP_ESMART_FMT_RGB888);

  /* REGION0 framebuffer physical start address (MMU bypass -> 32-bit pa). */

  rk3576_vop_putreg(priv, esmart_base + RK3576_VOP_ESMART_REGION0_YRGB_MST,
                    (uint32_t)up_addrenv_va_to_pa(priv->fbmem));

  /* Virtual stride in words: RGB888 -> (w*3/4) + (w%3). */

  vir_stride = ((uint32_t)xres * 3 / 4) + ((uint32_t)xres % 3);
  rk3576_vop_putreg(priv, esmart_base + RK3576_VOP_ESMART_REGION0_VIR,
                    vir_stride);

  /* Active region (w-1, h-1) and display region (same, no scaling),
   * display offset (0,0), scaling engine off.
   */

  rk3576_vop_putreg(priv, esmart_base + RK3576_VOP_ESMART_REGION0_ACT_INFO,
                    (((uint32_t)(yres - 1)) << 16) | (xres - 1));
  rk3576_vop_putreg(priv, esmart_base + RK3576_VOP_ESMART_REGION0_DSP_INFO,
                    (((uint32_t)(yres - 1)) << 16) | (xres - 1));
  rk3576_vop_putreg(priv, esmart_base + RK3576_VOP_ESMART_REGION0_DSP_OFF, 0);
  rk3576_vop_putreg(priv, esmart_base + RK3576_VOP_ESMART_REGION0_SCL_CTRL, 0);

  /* Route ESMART0 to this video port. */

  rk3576_vop_putreg(priv, esmart_base + RK3576_VOP_ESMART_PORT_SEL_IMD,
                    RK3576_VOP_ESMART_PORT_VP0);

  /* Enable REGION0: RGB888 + region enable.  (No rgb/bgr swap: the NuttX
   * framebuffer is stored R,G,B byte order, matching the VOP RGB888 path.)
   */

  ctrl = RK3576_VOP_ESMART_FMT_RGB888 | RK3576_VOP_ESMART_REGION0_MST_EN;
  rk3576_vop_putreg(priv, esmart_base + RK3576_VOP_ESMART_REGION0_CTRL, ctrl);

  /* OVERLAY: connect layer0 to ESMART0 (reset default is Disable, so this
   * is required for any window data to reach the POST block).
   */

  rk3576_vop_putreg(priv, ovl_base + RK3576_VOP_OVERLAY_LAYER_SEL,
                    RK3576_VOP_LAYER_SEL_L0(RK3576_VOP_LAYER_SEL_ESMART0) |
                        RK3576_VOP_LAYER_SEL_L1(
                            RK3576_VOP_LAYER_SEL_DISABLE) |
                        RK3576_VOP_LAYER_SEL_L2(
                            RK3576_VOP_LAYER_SEL_DISABLE) |
                        RK3576_VOP_LAYER_SEL_L3(
                            RK3576_VOP_LAYER_SEL_DISABLE));
}

/****************************************************************************
 * Name: rk3576_vop_configure_port
 *
 * Description:
 *   Program POSTx output mode (dsp_out_mode = RGB888), take the device out
 *   of standby, and route the selected interface to the selected port
 *   through SYS_CTRL_*_INFACE_CTRL.
 ****************************************************************************/

static void rk3576_vop_configure_port(FAR struct rk3576_vop_s *priv)
{
  uint32_t post_base = RK3576_VOP_POST(priv->base, priv->cfg.port);
  uint32_t sys_base = RK3576_VOP_SYS_CTRL(priv->base);
  uint32_t iface_off = g_rk3576_vop_iface_regs[priv->cfg.iface];
  uint32_t esmart_base = RK3576_VOP_ESMART(priv->base, 0);
  uint32_t regval;

  /* POST: RGB888 output mode, clear standby.  POST_DSP_CTRL is a mirror
   * register (reset value 0x8000000f: bit31 vop_standby_en=1, dsp_out_mode
   * =0xf).  Write the whole word with putreg -- do NOT use modifyreg, which
   * reads back the unloaded mirror (0) and can mis-handle the immediate
   * standby bit.  Value 0 = standby off + out_mode RGB888 + no black/blank.
   */

  rk3576_vop_putreg(priv, post_base + RK3576_VOP_POST_DSP_CTRL,
                    RK3576_VOP_POST_OUT_RGB888);

  /* Interface ctrl: select video port + enable output (and clock), while
   * preserving the reset-default sync polarities (Positive) and
   * regdone_imd_en.  MIPI0_INFACE_CTRL resets to vsync_pol=1/hsync_pol=1/
   * regdone_imd_en=1; writing the whole word would clear those and drive
   * inverted sync into the DSI IPI (which then never locks onto a frame).
   *
   * Set out_en + clk_out_en + port_sel, and keep hsync/vsync Positive +
   * regdone_imd_en (mirror -> real immediately).  cmd_mode stays 0 (Video).
   *
   * CRITICAL pixel-clock configuration (Linux rk3576_calc_cru_cfg()):
   * RK3576 VP0 is dual-pixel (pixel_rate=2), so the POST scan clock must be
   * HALF the panel pixel clock.  With dclk=64M the VOP-internal dclk_core
   * must be 32M (dclk/2), selected by POST_CORE_CLK.dclk_core_sel=1.  The
   * MIPI interface then takes dclk_core directly (mipi0_dclk_sel=0) and
   * divides by 2 (mipi0_pixclk_div=0) to feed the DSI IPI 16M
   * (= crtc_clock/4, matching PHY_IPI_RATIO=1.5).  Leaving dclk_core_sel=0
   * doubles the scan rate: dsp_vcnt0 runs at 2x and the pixel stream never
   * aligns with the DSI IPI clock domain -> all-black.
   */

  /* dclk_core_sel = 1 (dclk_core = dclk/2 = 32M), dclk_out_sel = 0. */

  rk3576_vop_putreg(priv, post_base + RK3576_VOP_POST_CORE_CLK,
                    RK3576_VOP_POST_CORE_CLK_DCLK_CORE_SEL);

  regval = RK3576_VOP_IFACE_CLK_OUT_EN | RK3576_VOP_IFACE_OUT_EN |
           RK3576_VOP_IFACE_VSYNC_POL | RK3576_VOP_IFACE_HSYNC_POL |
           RK3576_VOP_IFACE_REGDONE_IMD_EN |
           ((uint32_t)priv->cfg.port << RK3576_VOP_IFACE_PORT_SEL_SHIFT);
  rk3576_vop_modifyreg(priv, sys_base + iface_off,
                       RK3576_VOP_IFACE_OUT_EN | RK3576_VOP_IFACE_CLK_OUT_EN |
                           RK3576_VOP_IFACE_PORT_SEL_MASK |
                           RK3576_VOP_IFACE_POL_MASK |
                           RK3576_VOP_IFACE_REGDONE_IMD_EN,
                       regval);

  /* Fire the register-configure-done pulse (hiword write-mask scheme) to
   * copy all mirror registers (layer, overlay, POST timing/control) to
   * their real registers at the start of the next frame.
   *
   * Load every group: global0/1/2 (bit0/1/2) + sys0/1/2 (bit4/5/6), so the
   * POST DSP/timing registers land regardless of which group they live in.
   */

  rk3576_vop_putreg(priv, sys_base + RK3576_VOP_SYS_REG_CFG_DONE,
                    RK3576_VOP_CFG_DONE_LOAD_CTRL |
                        RK3576_VOP_CFG_DONE_ALL_GROUPS);

  /* The ESMART layer registers live in their own mirror set and must be
   * loaded via SYS_WIN_REG_CFG_DONE's reg_load_esmart0_en (a separate
   * trigger from the global/system cfg_done above).  Without it every
   * ESMART register reads back 0.
   */

  rk3576_vop_putreg(priv, sys_base + RK3576_VOP_SYS_WIN_REG_CFG_DONE,
                    RK3576_VOP_WIN_CFG_DONE_LOAD_CTRL |
                        RK3576_VOP_WIN_CFG_DONE_ESMART0);

  /* --- Probe A: immediately read back both cfg_done registers to prove
   * whether the reg_load_esmart0_en write actually latched (TRM says these
   * are ordinary RW bits that hold 1 until cleared -- so right after the
   * write, WIN_CFG_DONE low-16 must show bit4=1 and REG_CFG_DONE must show
   * bit15(sw_global_regdone_en, reset=1) still set).  If either reads 0
   * here, the hiword write-mask write is being swallowed. --- */

  syslog(LOG_INFO,
         "vop-probe-A: after cfg_done REG_CFG_DONE=%08x "
         "WIN_CFG_DONE=%08x\n",
         rk3576_vop_getreg(priv, sys_base + RK3576_VOP_SYS_REG_CFG_DONE),
         rk3576_vop_getreg(priv, sys_base + RK3576_VOP_SYS_WIN_REG_CFG_DONE));

  /* --- Probe B: read back the ESMART mirror registers right after the
   * load trigger.  NOTE: reading the *mirror* (unloaded) register shows the
   * value software wrote; the real-side copy only appears after a frame
   * boundary.  Compare these against the later "real" dump: if mirror has
   * the value but real=0, the load never crossed the frame boundary. --- */

  syslog(LOG_INFO,
         "vop-probe-B: ESMART0 CTRL0=%08x REGION0_CTRL=%08x "
         "YRGB_MST=%08x VIR=%08x (mirror/real ambiguous, compare w/ dump)\n",
         rk3576_vop_getreg(priv,
                           esmart_base + RK3576_VOP_ESMART_CTRL0),
         rk3576_vop_getreg(priv,
                           esmart_base + RK3576_VOP_ESMART_REGION0_CTRL),
         rk3576_vop_getreg(priv,
                           esmart_base + RK3576_VOP_ESMART_REGION0_YRGB_MST),
         rk3576_vop_getreg(priv,
                           esmart_base + RK3576_VOP_ESMART_REGION0_VIR));

  /* Bound the AXI0 outstanding transactions (IMD registers take effect
   * immediately, no cfg_done needed).  The ESMART scan-out DMA goes out on
   * axi0 (reset esmart_axi_sel=0), and with SYS_AXI0_CTRL_IMD at reset
   * (outstanding_en=0 = unlimited) it can monopolise the NoC and starve the
   * CPU, hanging the SoC.  outstanding_en=1 + num=16 caps the in-flight
   * bursts so the CPU keeps its DDR bandwidth.
   */

  rk3576_vop_putreg(priv, sys_base + RK3576_VOP_SYS_AXI0_CTRL_IMD,
                    RK3576_VOP_SYS_AXI_OUTSTANDING_EN |
                        RK3576_VOP_SYS_AXI_OUTSTANDING(16));
}

/****************************************************************************
 * Name: rk3576_vop_enable_clocks
 ****************************************************************************/

/* End of the VOP clock tree is the mux that selects the VOP AXI root and
 * the pixel-clock source.  Their HW reset value points at PLLs that are not
 * yet modelled in rk3576_clk_tree.c (clk_spll/clk_lpll/clk_vpll/clk_bpll are
 * orphan), so clk_get_rate() on aclk_vop reads back 0 even though the HW
 * clock may be running.  Zero aclk_vop leaves the ESMART/POST layers
 * unclocked (registers read back 0) -> all-black output.
 *
 * Until those PLLs are registered, force the VOP source muxes onto
 * clk_gpll (1188 MHz), which IS registered.  Temporary bring-up hack; remove
 * once the full PLL set is modelled.
 */

static void rk3576_vop_reparent_clocks(FAR struct rk3576_vop_s *priv)
{
  struct clk_s *gpll = clk_get("clk_gpll");
  struct clk_s *mux;
  int ret;

  if (gpll == NULL)
    {
      gerr("ERROR: VOP failed to get clk_gpll\n");
      return;
    }

  /* aclk_vop_root_sel: the AXI clock source mux (reset -> orphan PLL). */

  mux = clk_get("aclk_vop_root_sel");
  if (mux != NULL)
    {
      ret = clk_set_parent(mux, gpll);
      if (ret < 0)
        {
          gerr("ERROR: VOP failed to reparent aclk_vop_root_sel: %d\n", ret);
        }
    }

  /* Clamp aclk_vop to <= 700 MHz (TRM Part 2, 11.3.1: VOP ACLK max op
   * frequency is 700 MHz).  The orphan-PLL workaround above left
   * aclk_vop_root_div at its reset value (div-by-1), feeding clk_gpll's
   * raw 1188 MHz straight into the AXI domain -- well over the 700 MHz
   * design limit, which can lock the VOP BIU/AXI bus and hang the SoC.
   * Setting the rate propagates up and programs aclk_vop_root_div.
   */

  if (priv->aclk != NULL)
    {
      ret = clk_set_rate(priv->aclk, 594000000);
      if (ret < 0)
        {
          gerr("ERROR: VOP failed to set aclk_vop rate below 700MHz: %d\n",
               ret);
        }
    }

  /* dclk_vpN_sel: final pixel-clock select (0 = *_src, 1 = hdmiphy pixel).
   * Force onto the src path so the divider chain below can drive the rate.
   */

  mux = clk_get(g_rk3576_vop_dclk_names[priv->cfg.port]);
  if (mux != NULL)
    {
      /* Reparent the *_src_sel mux (the 3-bit PLL selector) onto gpll. */
      char src_sel_name[24];

      snprintf(src_sel_name, sizeof(src_sel_name), "%s_src_sel",
               g_rk3576_vop_dclk_names[priv->cfg.port]);
      mux = clk_get(src_sel_name);
      if (mux != NULL)
        {
          ret = clk_set_parent(mux, gpll);
          if (ret < 0)
            {
              gerr("ERROR: VOP failed to reparent %s: %d\n", src_sel_name,
                   ret);
            }
        }
    }
}

static int rk3576_vop_enable_clocks(FAR struct rk3576_vop_s *priv)
{
  static const char *const biu_clocks[] = {
    "aclk_vop_biu",
    "aclk_vop2_biu",
    "hclk_vop_biu",
    "pclk_vop_biu",
  };
  struct clk_s *biu;
  int ret;
  int i;

  priv->aclk = clk_get(RK3576_VOP_ACLK_NAME);
  if (priv->aclk == NULL)
    {
      gerr("ERROR: VOP failed to get %s\n", RK3576_VOP_ACLK_NAME);
      return -ENODEV;
    }

  priv->hclk = clk_get(RK3576_VOP_HCLK_NAME);
  if (priv->hclk == NULL)
    {
      gerr("ERROR: VOP failed to get %s\n", RK3576_VOP_HCLK_NAME);
      return -ENODEV;
    }

  priv->dclk = clk_get(g_rk3576_vop_dclk_names[priv->cfg.port]);
  if (priv->dclk == NULL)
    {
      gerr("ERROR: VOP failed to get %s\n",
           g_rk3576_vop_dclk_names[priv->cfg.port]);
      return -ENODEV;
    }

  /* Force orphan PLL muxes onto clk_gpll before enabling (temporary). */

  rk3576_vop_reparent_clocks(priv);

  /* Set the pixel clock to the panel's needs (64 MHz for kickpi-k7).
   * The rate propagates up through dclk_vpN_sel/_src/_src_div/_src_sel.
   */

  ret = clk_set_rate(priv->dclk, 64000000);
  if (ret < 0)
    {
      gerr("ERROR: VOP failed to set %s rate: %d\n",
           g_rk3576_vop_dclk_names[priv->cfg.port], ret);
      return ret;
    }

  /* Enable the VOP BIU (bus-interface-unit) clocks.  The ESMART/POST layers
   * reach DDR over the VOP AXI port, which is clocked by aclk_vop_biu /
   * hclk_vop_biu (CON61[4]/[6]); these gates are SET_TO_DISABLE and are NOT
   * auto-enabled by enabling aclk_vop.  If they stay gated, the very first
   * ESMART scan-out AXI read enters a clockless BIU and pends forever,
   * seizing a NoC outstanding slot and starving the CPU's DDR traffic ->
   * the whole SoC hangs right after nsh starts.  This is the actual VOP
   * hang root cause (not the AXI outstanding limit).
   */

  for (i = 0; i < nitems(biu_clocks); i++)
    {
      biu = clk_get(biu_clocks[i]);
      if (biu == NULL)
        {
          continue; /* Not registered: skip (older clock trees). */
        }

      ret = clk_enable(biu);
      if (ret < 0)
        {
          gerr("ERROR: VOP failed to enable %s: %d\n", biu_clocks[i], ret);
        }
    }

  ret = clk_enable(priv->aclk);
  if (ret < 0)
    {
      gerr("ERROR: VOP failed to enable aclk_vop: %d\n", ret);
      return ret;
    }

  ret = clk_enable(priv->hclk);
  if (ret < 0)
    {
      gerr("ERROR: VOP failed to enable hclk_vop: %d\n", ret);
      clk_disable(priv->aclk);
      return ret;
    }

  ret = clk_enable(priv->dclk);
  if (ret < 0)
    {
      gerr("ERROR: VOP failed to enable %s: %d\n",
           g_rk3576_vop_dclk_names[priv->cfg.port], ret);
      clk_disable(priv->hclk);
      clk_disable(priv->aclk);
      return ret;
    }

  return OK;
}

/****************************************************************************
 * Name: rk3576_vop_reset
 *
 * Description:
 *   Release (de-assert) the VOP core resets.  The CRU reset bits are
 *   "When high, reset relative logic", so write 0 (with hiword write-mask)
 *   to release.  Only the de-assert side is written: pulsing the assert
 *   side tears down the already-clocked BIU's AXI transactions and hangs
 *   the NoC/DDR (SoC-wide hang).
 ****************************************************************************/

static void rk3576_vop_reset(FAR struct rk3576_vop_s *priv)
{
  uint32_t reg = RK3576_CRU_ADDR + RK3576_CRU_SOFTRST_CON(RK3576_VOP_RST_CON);

  /* De-assert (release) the VOP core only.  Do NOT pulse the assert side:
   * asserting aresetn_biu/hresetn_biu while the VOP AXI master is already
   * clocked (clk_enable above) tears down in-flight AXI transactions and
   * leaves a hung outstanding slot on the NoC/DDR that then starves the
   * CPU's DDR traffic -> SoC hang (this was the observed root cause).
   *
   * The VOP is already out of reset from the boot stage, so a deassert-only
   * write (data 0) is sufficient; the reset bits are "When high, reset" so
   * writing 0 releases them without disturbing a live bus interface.
   */

  putreg32(RK3576_VOP_HWM(RK3576_VOP_RST_MAIN_MASK), reg);
  up_udelay(20);
}

/****************************************************************************
 * Name: rk3576_vop_power_on_esmart
 *
 * Description:
 *   Power on the VOP_ESMART power domain and release the ESMART layer from
 *   its frame reset.  The ESMART layer has no standalone clock gate in the
 *   CRU; its aclk_esmart0..3 are derived from aclk_vop by the VOP-internal
 *   ESMART_PD_CRU once the PD_VOP_ESMART domain is up.
 *
 *   Steps:
 *     1. Release the BISR initial reset (initrst) for PD_VOP + PD_VOP_ESMART
 *        + PD_VOP_CLUSTER in PMU_BISR_INITRST_SFTCON0 (1 = Normal).  Until
 *        this is done the PD reset (aresetn_pd) is asserted and the ESMART
 *        layer clock (aclk_esmart0..3) never comes up, so every ESMART
 *        register reads back 0.
 *     2. Clear pd_vop_dwn_ena and pd_vop_esmart_dwn_ena in
 *        PMU_PWR_GATE_CON0 so both domains stay powered ('0' = keep powered,
 *        hiword mask).
 *     3. De-assert esmart_frm_resetn_en (ESMART0_CTRL0 bit 31) so the esmart
 *        layer leaves reset.
 ****************************************************************************/

static void rk3576_vop_power_on_esmart(FAR struct rk3576_vop_s *priv)
{
  uint32_t pmu_pwr =
      RK3576_PMU_ADDR + RK3576_VOP_PMU_PWR_GATE_CON0_OFF;
  uint32_t pmu_initrst =
      RK3576_PMU_ADDR + RK3576_VOP_PMU_BISR_INITRST_SFTCON0_OFF;
  uint32_t esmart_base = RK3576_VOP_ESMART(priv->base, 0);

  /* 1. Release the PD memory-repair initial reset (write 1 = Normal).  This
   * is the aresetn_pd source for the ESMART/CLUSTER block diagrams; without
   * it the ESMART layer clock never starts. */

  putreg32(RK3576_VOP_HWM(RK3576_VOP_INITRST_RELEASE_MASK) |
               RK3576_VOP_INITRST_RELEASE_MASK,
           pmu_initrst);
  up_udelay(20);

  /* 2. Keep PD_VOP and PD_VOP_ESMART powered: write-enable both bits (mask)
   * with data 0 (so *_dwn_ena = 0 -> not powered down). */

  putreg32(RK3576_VOP_HWM(RK3576_VOP_PD_VOP_ESMART_DWN_ENA |
                          RK3576_VOP_PD_VOP_DWN_ENA),
           pmu_pwr);
  up_udelay(20);

  /* 3. Release the esmart layer from frame reset (active: bit set = normal). */

  rk3576_vop_putreg(priv, esmart_base + RK3576_VOP_ESMART_CTRL0,
                    RK3576_VOP_ESMART_CTRL0_FRM_RESETN_EN);
}

/****************************************************************************
 * Public Functions
 ****************************************************************************/

/****************************************************************************
 * Name: rk3576_vop_initialize
 ****************************************************************************/

int rk3576_vop_initialize(FAR const struct rk3576_vop_config *config)
{
  FAR struct rk3576_vop_s *priv;
  int ret;

  DEBUGASSERT(config != NULL);

  if (config->iface >= RK3576_VOP_IFACE_MAX || config->port > 2)
    {
      gerr("ERROR: VOP invalid routing (iface=%d port=%d)\n", config->iface,
           config->port);
      return -EINVAL;
    }

  priv = kmm_zalloc(sizeof(struct rk3576_vop_s));
  if (priv == NULL)
    {
      return -ENOMEM;
    }

  memcpy(&priv->vtable, &g_rk3576_vop_vtable, sizeof(struct fb_vtable_s));
  memcpy(&priv->cfg, config, sizeof(struct rk3576_vop_config));
  priv->base = RK3576_VOP_ADDR;

  /* Framebuffer geometry (RGB888, 3 bytes/pixel). */

  priv->stride = (uint32_t)config->xres * 3;
  priv->fblen = (size_t)priv->stride * config->yres;

  /* Allocate the framebuffer from the DMA heap (<4GB, physically
   * contiguous, identity mapped).
   */

  priv->fbmem = rk3576_dma_alloc(priv->fblen);
  if (priv->fbmem == NULL)
    {
      gerr("ERROR: VOP failed to allocate %zu-byte framebuffer\n",
           priv->fblen);
      ret = -ENOMEM;
      goto errout_with_priv;
    }

  /* Fill the framebuffer with a 16x16-pixel black/white checkerboard test
   * pattern (each cell RWGB888 -> 0x00/0xff for every byte).  A uniform
   * fill (0xff or 0x00) makes every byte identical, so the MIPI data lane
   * carries a constant bit stream with no transitions -- useless for
   * verifying pixel packing on the scope.  The checkerboard toggles the
   * bytes so the HS data lanes visibly toggle while scanning. */

  {
    uint8_t *fb = (uint8_t *)priv->fbmem;
    uint32_t x;
    uint32_t y;

    for (y = 0; y < priv->cfg.yres; y++)
      {
        for (x = 0; x < priv->cfg.xres; x++)
          {
            uint8_t v = (((x / 16u) + (y / 16u)) & 1u) ? 0xff : 0x00;
            uint32_t p = (y * priv->stride) + (x * 3);

            fb[p + 0] = v; /* R */
            fb[p + 1] = v; /* G */
            fb[p + 2] = v; /* B */
          }
      }
  }

  /* Bring up clocks and release resets. */

  ret = rk3576_vop_enable_clocks(priv);
  if (ret < 0)
    {
      goto errout_with_fb;
    }

  rk3576_vop_reset(priv);

  /* Power on the ESMART domain and release the esmart layer reset before
   * touching any ESMART registers (aclk_esmart derives from this domain). */

  rk3576_vop_power_on_esmart(priv);

  /* Program layer, timing and output routing. */

  rk3576_vop_configure_layer(priv);
  rk3576_vop_configure_timing(priv);
  rk3576_vop_configure_port(priv);

  /* --- Temporary bring-up diagnostics (B: dump, no behaviour change) ---
   * 1. Clock rates: dclk_vp0 must be 64MHz to match the DSI IPI's
   *    phy_ipi_ratio (hs_rate / pixel_clock).  Its misprogramming is the
   *    prime suspect for "command link up but all-black video".
   * 2. Framebuffer VA/PA: identity-mapped -> equal; a mismatch means the
   *    ESMART DMA is reading the wrong address.
   * 3. Register readbacks: confirm the mirror->real copy took effect.
   */

  {
    uint32_t esmart_base = RK3576_VOP_ESMART(priv->base, 0);
    uint32_t ovl_base = RK3576_VOP_OVERLAY_PORT(priv->base, priv->cfg.port);
    uint32_t post_base = RK3576_VOP_POST(priv->base, priv->cfg.port);
    uint32_t sys_base = RK3576_VOP_SYS_CTRL(priv->base);
    uint32_t iface_off = g_rk3576_vop_iface_regs[priv->cfg.iface];
    uintptr_t fb_pa = up_addrenv_va_to_pa(priv->fbmem);

    /* Power-domain state (PMU@0x27360000).  PD_VOP_ESMART/PD_VOP must be
     * "Power up" (status bit 0) before the ESMART layer's aclk_esmart0 clock
     * is generated and its REGFILE becomes readable.  A readback of 0 from
     * every ESMART register above is the tell-tale of a down power domain. */

    syslog(LOG_INFO,
           "vop-dump: PMU PWR_GATE_STS=%08x (vop[11]=%u esmart[12]=%u "
           "cluster[13]=%u; 1=down)\n",
           getreg32(RK3576_PMU_ADDR + 0x20230),
           (getreg32(RK3576_PMU_ADDR + 0x20230) >> 11) & 1,
           (getreg32(RK3576_PMU_ADDR + 0x20230) >> 12) & 1,
           (getreg32(RK3576_PMU_ADDR + 0x20230) >> 13) & 1);

    syslog(LOG_INFO,
           "vop-dump: PMU PWR_GATE_SFTCON0=%08x CON0=%08x "
           "CHAIN0_STS0=%08x INITRST_SFTCON0=%08x\n",
           getreg32(RK3576_PMU_ADDR + 0x20210),
           getreg32(RK3576_PMU_ADDR + 0x20200),
           getreg32(RK3576_PMU_ADDR + 0x20240),
           getreg32(RK3576_PMU_ADDR + 0x20540));

    syslog(LOG_INFO,
           "vop-dump: aclk_vop=%lu hclk_vop=%lu dclk_vp%u=%lu "
           "(expect dclk=64000000)\n",
           (unsigned long)clk_get_rate(priv->aclk),
           (unsigned long)clk_get_rate(priv->hclk),
           (unsigned int)priv->cfg.port,
           (unsigned long)clk_get_rate(priv->dclk));

    syslog(LOG_INFO,
           "vop-dump: fbmem va=%p pa=%p (expect equal) stride=%u fblen=%u\n",
           priv->fbmem, (void *)fb_pa, priv->stride, (unsigned int)priv->fblen);

    /* --- Probe C: read the WIN_CFG_DONE / REG_CFG_DONE a second time (now
     * several ms after configure_port fired them).  TRM says a load bit
     * holds 1 "until cleared", so if it was 1 in probe-A and 0 here, some
     * later write or a frame-boundary auto-clear wiped it. --- */

    syslog(LOG_INFO,
           "vop-probe-C: now REG_CFG_DONE=%08x WIN_CFG_DONE=%08x\n",
           rk3576_vop_getreg(priv, sys_base + RK3576_VOP_SYS_REG_CFG_DONE),
           rk3576_vop_getreg(priv, sys_base + RK3576_VOP_SYS_WIN_REG_CFG_DONE));

    {
      uint32_t esmart_ctrl0 =
        rk3576_vop_getreg(priv, esmart_base + RK3576_VOP_ESMART_CTRL0);

      syslog(LOG_INFO,
             "vop-dump: ESMART0 CTRL0=%08x (frm_resetn_en[bit31]=%u) "
             "REGION0_CTRL=%08x YRGB_MST=%08x VIR=%08x\n",
             esmart_ctrl0,
             (unsigned)((esmart_ctrl0 >> 31) & 1),
             rk3576_vop_getreg(priv,
                               esmart_base + RK3576_VOP_ESMART_REGION0_CTRL),
             rk3576_vop_getreg(priv,
                               esmart_base + RK3576_VOP_ESMART_REGION0_YRGB_MST),
             rk3576_vop_getreg(priv,
                               esmart_base + RK3576_VOP_ESMART_REGION0_VIR));
    }

    syslog(LOG_INFO,
           "vop-dump: OVERLAY_PORT%u_LAYER_SEL=%08x (expect layer0=Esmart0)\n",
           (unsigned int)priv->cfg.port,
           rk3576_vop_getreg(priv, ovl_base + RK3576_VOP_OVERLAY_LAYER_SEL));

    {
      uint32_t iface =
        rk3576_vop_getreg(priv, sys_base + iface_off);

      syslog(LOG_INFO,
             "vop-dump: POST%u_DSP_CTRL=%08x MIPI0_INFACE_CTRL=%08x "
             "REG_CFG_DONE=%08x WIN_CFG_DONE=%08x\n",
             (unsigned int)priv->cfg.port,
             rk3576_vop_getreg(priv, post_base + RK3576_VOP_POST_DSP_CTRL),
             iface,
             rk3576_vop_getreg(priv, sys_base + RK3576_VOP_SYS_REG_CFG_DONE),
             rk3576_vop_getreg(priv,
                               sys_base + RK3576_VOP_SYS_WIN_REG_CFG_DONE));

      syslog(LOG_INFO,
             "vop-dump: INFACE out_en=%u clk_out_en=%u port_sel=%u "
             "hsync_pol=%u vsync_pol=%u cmd_mode=%u dclk_sel=%u "
             "pix_clk_sel=%u\n",
             (unsigned)(iface & RK3576_VOP_IFACE_OUT_EN) != 0,
             (unsigned)((iface >> 1) & 1),
             (unsigned)((iface >> RK3576_VOP_IFACE_PORT_SEL_SHIFT) & 0x3),
             (unsigned)((iface >> 4) & 1),
             (unsigned)((iface >> 5) & 1),
             (unsigned)((iface >> 11) & 1),
             (unsigned)((iface >> 21) & 1),
             (unsigned)((iface >> 20) & 1));
    }

    syslog(LOG_INFO,
           "vop-dump: POST%u HTOTAL=%08x HACT=%08x VTOTAL=%08x VACT=%08x "
           "MIPI_CTRL=%08x CORE_CLK=%08x\n",
           (unsigned int)priv->cfg.port,
           rk3576_vop_getreg(priv,
                             post_base + RK3576_VOP_POST_DSP_HTOTAL_HS_END),
           rk3576_vop_getreg(priv,
                             post_base + RK3576_VOP_POST_DSP_HACT_ST_END),
           rk3576_vop_getreg(priv,
                             post_base + RK3576_VOP_POST_DSP_VTOTAL_VS_END),
           rk3576_vop_getreg(priv,
                             post_base + RK3576_VOP_POST_DSP_VACT_ST_END),
           rk3576_vop_getreg(priv, post_base + RK3576_VOP_POST_MIPI_CTRL),
           rk3576_vop_getreg(priv, post_base + RK3576_VOP_POST_CORE_CLK));

    /* Decisive scan-state probe: dsp_vcnt0 is the VP0 vertical counter,
     * monotonically incrementing while the VP0 scan state machine runs.  A
     * value stuck at 0 proves VOP is NOT scanning (no pixel clock reaching
     * POST), which is the only remaining explanation for a fully-configured
     * but silent DSI IPI.  Read it twice with a short delay to observe any
     * increment; also dump the vsync-to-IO routing / DSI side IPI busy. */

    {
      uint32_t vcnt0 = rk3576_vop_getreg(priv,
                                         sys_base + RK3576_VOP_SYS_STATUS0);
      uint32_t vcnt_after;

      up_udelay(2000); /* ~2 ms, several scan lines at 64 MHz */

      vcnt_after = rk3576_vop_getreg(priv,
                                     sys_base + RK3576_VOP_SYS_STATUS0);

      {
        uint32_t v0 = (vcnt0 >> RK3576_VOP_DSP_VCNT0_SHIFT) & 0x1fff;
        uint32_t v1 = (vcnt_after >> RK3576_VOP_DSP_VCNT0_SHIFT) & 0x1fff;
        uint32_t vtotal = priv->cfg.yres + priv->cfg.vsync_len +
                          priv->cfg.vfront_porch + priv->cfg.vback_porch;

        /* 2 ms sample -> lines/sec = (delta * 500).  For a dual-pixel VP0
         * the vertical counter should advance ~ vtotal lines per frame at
         * 60 Hz (about 77700 lines/sec for 1280x1295).  A ~2x rate (=
         * 152500) means the scan timing / pixel clock is mismatched. */

        syslog(LOG_INFO,
               "vop-dump: SYS_STATUS0=%08x (dsp_vcnt0=%u) then %08x "
               "(dsp_vcnt0=%u) delta=%u lines/2ms=%u lines/s "
               "(expect ~%u @60Hz) VSYNC_CTRL=%08x\n",
               vcnt0, v0, vcnt_after, v1, (v1 - v0), (v1 - v0) * 500,
               vtotal * 60,
               rk3576_vop_getreg(priv,
                                 sys_base + RK3576_VOP_SYS_VSYNC_CTRL));
      }
    }
  }

  /* Self-register the framebuffer device. */

  ret = fb_register_device(config->display, config->plane, &priv->vtable);
  if (ret < 0)
    {
      gerr("ERROR: VOP fb_register_device() failed: %d\n", ret);
      goto errout_with_clocks;
    }

  return OK;

errout_with_clocks:
  clk_disable(priv->dclk);
  clk_disable(priv->hclk);
  clk_disable(priv->aclk);

errout_with_fb:
  rk3576_dma_free(priv->fbmem, priv->fblen);

errout_with_priv:
  kmm_free(priv);
  return ret;
}

#endif /* CONFIG_RK3576_VOP */
